ALTER TABLE board DROP FOREIGN KEY board_to_member_fk;
ALTER TABLE board ADD CONSTRAINT FOREIGN KEY (userid) REFERENCES ssafy_member(userid) ON DELETE CASCADE;
ALTER TABLE comment DROP FOREIGN KEY comment_ibfk_1;
ALTER TABLE comment DROP FOREIGN KEY comment_ibfk_2;
ALTER TABLE comment ADD CONSTRAINT FOREIGN KEY (userid) REFERENCES ssafy_member(userid) ON DELETE CASCADE;
ALTER TABLE comment ADD CONSTRAINT FOREIGN KEY (articleno) REFERENCES board(articleno) ON DELETE CASCADE;